Created GitHub actions
sliit-foss/student-sorter pull request #7
Opened 2022-01-18 11:25 UTC by methminug

Fixes #5 
Fixes #4 
Fixes #3

2022-01-18 11:42 UTC, Shehanka requested changes

2022-01-18 11:42 UTC, Shehanka commented on .vscode/settings.json
> +}
@methminug we should not push vs code settings to GitHub. so please put `.vscode` folder in gitignore

2022-01-18 12:35 UTC, methminug commented on .vscode/settings.json
> +}
Added .vscode/* to gitignore

2022-01-18 22:36 UTC, Shehanka requested changes

2022-01-18 22:36 UTC, Shehanka commented on .gitignore
> +# !.vscode/extensions.json
remove these lines. since you have ignored entire directory no need include files individually

2022-01-18 22:36 UTC, Shehanka commented on .vscode/settings.json
> +}
Run this command to remove this directory from git cache `git rm -rf --cached .vscode`

2022-01-19 16:02 UTC, Shehanka approved these changes
Good Job

2022-01-27 15:48 UTC, merged